import { Fragrance } from './types'

export const SEED_FRAGRANCES: Fragrance[] = [
  {
    id: '1',
    slug: 'creed-aventus',
    name: 'Aventus',
    brand: { id: 'b1', slug: 'creed', name: 'Creed', country: 'France' },
    description: 'A masterful woody-chypre for men. Inspired by Napoleon Bonaparte.',
    year: 2010,
    concentration: 'EDP',
    gender: 'masculine',
    accords: [
      { name: 'Fruity', percentage: 30 },
      { name: 'Citrus', percentage: 25 },
      { name: 'Woody',  percentage: 28 },
      { name: 'Smoky',  percentage: 17 },
    ],
    top_notes:   [{ id: 'n1', name: 'Pineapple', family: 'fruity' }, { id: 'n2', name: 'Blackcurrant', family: 'fruity' }, { id: 'n3', name: 'Bergamot', family: 'citrus' }, { id: 'n4', name: 'Apple', family: 'fruity' }],
    heart_notes: [{ id: 'n5', name: 'Birch', family: 'woody' }, { id: 'n6', name: 'Rose', family: 'floral' }, { id: 'n7', name: 'Jasmine', family: 'floral' }, { id: 'n8', name: 'Patchouli', family: 'woody' }],
    base_notes:  [{ id: 'n9', name: 'Ambergris', family: 'musky' }, { id: 'n10', name: 'Oak Moss', family: 'woody' }, { id: 'n11', name: 'Vanilla', family: 'amber' }, { id: 'n12', name: 'Musk', family: 'musky' }],
    avg_score: 9.8,
    rating_count: 31420,
    recommend_pct: 94,
    longevity_dist: { '24hrs+': 12, '12-24hrs': 28, '8-12hrs': 38, '4-8hrs': 16, 'under-4hrs': 6 },
    sillage_dist: { enormous: 18, strong: 42, moderate: 28, soft: 8, intimate: 4 },
    gender_dist: { masculine: 71, feminine: 29, unisex: 0 },
    prices: [
      { id: 'p1', retailer: { id: 'r1', name: 'Creed Official' },     size_ml: 100, price: 275, currency: 'GBP', affiliate_url: '#' },
      { id: 'p2', retailer: { id: 'r2', name: 'John Lewis' },         size_ml: 100, price: 239, currency: 'GBP', affiliate_url: '#' },
      { id: 'p3', retailer: { id: 'r3', name: 'Harrods' },            size_ml: 100, price: 264, currency: 'GBP', affiliate_url: '#' },
      { id: 'p4', retailer: { id: 'r4', name: 'Selfridges' },         size_ml: 100, price: 258, currency: 'GBP', affiliate_url: '#' },
    ],
  },
  {
    id: '2',
    slug: 'mfk-baccarat-rouge-540',
    name: 'Baccarat Rouge 540',
    brand: { id: 'b2', slug: 'maison-francis-kurkdjian', name: 'Maison Francis Kurkdjian', country: 'France' },
    year: 2015, concentration: 'EDP', gender: 'unisex',
    accords: [
      { name: 'Amber',  percentage: 38 },
      { name: 'Musky',  percentage: 28 },
      { name: 'Floral', percentage: 22 },
      { name: 'Woody',  percentage: 12 },
    ],
    avg_score: 9.6, rating_count: 12400, recommend_pct: 91,
    prices: [{ id: 'p5', retailer: { id: 'r1', name: 'MFK Official' }, size_ml: 100, price: 195, currency: 'GBP', affiliate_url: '#' }],
  },
  {
    id: '3',
    slug: 'dior-sauvage-edp',
    name: 'Sauvage EDP',
    brand: { id: 'b3', slug: 'dior', name: 'Dior', country: 'France' },
    year: 2018, concentration: 'EDP', gender: 'masculine',
    accords: [
      { name: 'Fresh', percentage: 35 },
      { name: 'Spicy', percentage: 28 },
      { name: 'Woody', percentage: 22 },
      { name: 'Green', percentage: 15 },
    ],
    avg_score: 8.8, rating_count: 44800, recommend_pct: 87,
    prices: [{ id: 'p6', retailer: { id: 'r2', name: 'John Lewis' }, size_ml: 60, price: 62, currency: 'GBP', affiliate_url: '#' }],
  },
  {
    id: '4',
    slug: 'tom-ford-black-orchid',
    name: 'Black Orchid',
    brand: { id: 'b4', slug: 'tom-ford', name: 'Tom Ford', country: 'USA' },
    year: 2006, concentration: 'EDP', gender: 'unisex',
    accords: [
      { name: 'Oud',   percentage: 32 },
      { name: 'Floral', percentage: 28 },
      { name: 'Spicy', percentage: 22 },
      { name: 'Woody', percentage: 18 },
    ],
    avg_score: 9.2, rating_count: 8200, recommend_pct: 89,
    prices: [{ id: 'p7', retailer: { id: 'r3', name: 'Harrods' }, size_ml: 100, price: 118, currency: 'GBP', affiliate_url: '#' }],
  },
  {
    id: '5',
    slug: 'ysl-black-opium',
    name: 'Black Opium',
    brand: { id: 'b5', slug: 'ysl', name: 'YSL', country: 'France' },
    year: 2014, concentration: 'EDP', gender: 'feminine',
    accords: [
      { name: 'Dark',   percentage: 30 },
      { name: 'Amber',  percentage: 28 },
      { name: 'Floral', percentage: 26 },
      { name: 'Citrus', percentage: 16 },
    ],
    avg_score: 8.9, rating_count: 22100, recommend_pct: 88,
    prices: [{ id: 'p8', retailer: { id: 'r2', name: 'John Lewis' }, size_ml: 50, price: 72, currency: 'GBP', affiliate_url: '#' }],
  },
  {
    id: '6',
    slug: 'chanel-n5-leau',
    name: "N°5 L'Eau",
    brand: { id: 'b6', slug: 'chanel', name: 'Chanel', country: 'France' },
    year: 2016, concentration: 'EDT', gender: 'feminine',
    accords: [
      { name: 'Floral',  percentage: 38 },
      { name: 'Musky',   percentage: 28 },
      { name: 'Fresh',   percentage: 20 },
      { name: 'Citrus',  percentage: 14 },
    ],
    avg_score: 8.6, rating_count: 19300, recommend_pct: 85,
    prices: [{ id: 'p9', retailer: { id: 'r3', name: 'Harrods' }, size_ml: 100, price: 98, currency: 'GBP', affiliate_url: '#' }],
  },
]

export const SEED_DUPES = [
  { id: 'd1', original_slug: 'creed-aventus', dupe_name: 'Vibrant Leather', dupe_brand: 'Zara', match_pct: 89, price: 18, saves: 257, vote_count: 4201 },
  { id: 'd2', original_slug: 'creed-aventus', dupe_name: 'Invictus Legend', dupe_brand: 'Paco Rabanne', match_pct: 83, price: 68, saves: 207, vote_count: 2890 },
  { id: 'd3', original_slug: 'creed-aventus', dupe_name: 'Phantom EDT', dupe_brand: 'Rabanne', match_pct: 79, price: 56, saves: 219, vote_count: 1443 },
]
